name: Запуск тестов LeetCode

on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Запуск тестов во всех проектах с Microsoft.NET.Test.Sdk
        run: |
          echo "Поиск тестовых проектов..."
          for proj in $(find . -name "*_Solution.csproj"); do
            echo "🧪 Запуск тестов в $proj"
            dotnet test "$proj" --no-restore --collect:"XPlat Code Coverage"
          done

      - name: Обновление README списком решенных задач
        run: |
          echo "📄 Генерация списка решенных задач..."
          echo "# Решенные задачи LeetCode" > README.md
          echo "" >> README.md
          find . -name "*_Solution.csproj" | sort | while read proj; do
            # Извлечение имени задачи из пути
            task=$(basename "$proj" .csproj | sed 's/_Solution$//')
            echo "- $task" >> README.md
          done
          echo "" >> README.md
          echo "✅ Обновлено $(date -u)" >> README.md

      - name: Коммит README при наличии изменений
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [[ -n "$(git status --porcelain README.md)" ]]; then
            git add README.md
            git commit -m "📘 Обновление списка решенных задач"
            git push
          else
            echo "📄 Нет изменений для коммита."
          fi