name: Run LeetCode Tests

on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests in all projects with Microsoft.NET.Test.Sdk
        run: |
          echo "Finding test projects..."
          for proj in $(find . -name "LeetCode.*_Solution.csproj"); do
            echo "🧪 Running tests in $proj"
            dotnet test "$proj" --collect:"XPlat Code Coverage" ...
          done
