name: Run LeetCode Tests

on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests in all projects with Microsoft.NET.Test.Sdk
        run: |
          echo "Finding test projects..."
            for proj in $(find . -name "*_Solution.csproj"); do
              echo "🧪 Running tests in $proj"
              dotnet test "$proj" --collect:"XPlat Code Coverage" ...
            done
      - name: Update README with solved problems
        run: |
          echo "📄 Generating list of solved problems..."

          echo "# Solved LeetCode Problems" > README.md
          echo "" >> README.md

          find . -name "*_Solution.csproj" | sort | while read proj; do
            # Извлечь имя задачи из пути
            task=$(basename "$proj" .csproj | sed 's/_Solution$//')
            echo "- $task" >> README.md
          done

          echo "" >> README.md
          echo "✅ Updated on $(date -u)" >> README.md

      - name: Commit README if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if [[ -n "$(git status --porcelain README.md)" ]]; then
            git add README.md
            git commit -m "📘 Update solved problems list"
            git push
          else
            echo "📄 No changes to commit."
          fi

